# Generated by Django 5.0.6 on 2024-06-02 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_userole'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userole',
            new_name='user_role',
        ),
    ]
