# Generated by Django 5.0.6 on 2024-06-07 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_student_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentHomework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mavzu', models.CharField(max_length=200)),
                ('video', models.IntegerField()),
                ('vazifa', models.CharField(choices=[('qabul', 'Qabul qilingan'), ('bajarilmagan', 'Bajarilmagan'), ('berilmagan', 'Kerilmagan'), ('kutilayotganlar', 'Kutilayotganlar')], default='Berilmagan', max_length=20)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('date_lesson', models.DateField(blank=True, null=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.student')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.team')),
            ],
        ),
    ]
