# Generated by Django 5.0.6 on 2024-06-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_studenthomework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenthomework',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
