# Generated by Django 5.0.6 on 2024-06-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_studenthomework_date_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenthomework',
            name='vazifa',
            field=models.CharField(choices=[('qabul', 'Qabul qilingan'), ('bajarilmagan', 'Bajarilmagan'), ('berilmagan', 'Berilmagan'), ('kutilayotganlar', 'Kutilayotganlar')], default='Berilmagan', max_length=20),
        ),
    ]
