# Generated by Django 5.0.6 on 2024-06-08 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('users', '0013_alter_studenthomework_vazifa'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Homework',
            new_name='Lesson',
        ),
    ]
