# Generated by Django 5.0.6 on 2024-06-08 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_homework'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='dascritption',
            new_name='dascription',
        ),
    ]
